<?php

namespace Database\Seeders;

use App\Models\KodeTransaksi;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class KodeTransaksiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $kode_biaya = [
            [
                'kode' => 101,
                'nama_transaksi' => 'BIAYA PEKERJA : UPAH POKOK',
                'desc' => 'Merupakan salah satu komponen upah yang bersifat tetap berdasarkan pada golongan pekerja.',
                'jenis_kode' => 'Biaya',
                'kategori' => 'SDM',
            ],
            [
                'kode' => 102,
                'nama_transaksi' => 'BIAYA PEKERJA : KOREKSI UPAH',
                'desc' => 'Merupakan koreksi atas imbalan dasar yang dibayarkan kepada pekerja menurut tingkat atau jenis pekerjaan yang besarnya ditetapkan berdasarkan kesepakatan.',
                'jenis_kode' => 'Biaya',
                'kategori' => 'SDM',
            ],
            [
                'kode' => 103,
                'nama_transaksi' => 'BIAYA PEKERJA : TUNJANGAN JABATAN',
                'desc' => 'a.    Tunjangan jabatan dan besarannya diberikan kepada pekerja yang menduduki jabatan-jabatan yang telah ditetapkan oleh Surat Keputusan Direksi. b.    Pekerja yang tidak lagi memangku jabatan, maka tunjangan jabatan tidak diberikan',
                'jenis_kode' => 'Biaya',
                'kategori' => 'SDM',
            ],
            [
                'kode' => 104,
                'nama_transaksi' => 'BIAYA PEKERJA : TUNJANGAN DAERAH',
                'desc' => 'Tunjangan yang dibayarkan sesuai dengan tingkat kemahalan berdasarkan indeks harga yang berlaku di daerah masing-masing.',
                'jenis_kode' => 'Biaya',
                'kategori' => 'SDM',
            ],
            [
                'kode' => 105,
                'nama_transaksi' => 'BIAYA PEKERJA : TUNJANGAN HARI RAYA ( THR )',
                'desc' => 'a.    Perusahaan memberikan Tunjangan Hari Raya (THR) keagamaan bagi pekerja yang telah bekerja sekurang-kurangnya 12 (dua belas) bulan berturut-turut. b.    Tunjangan Hari Raya (THR) keagamaan  ini diberikan 1 (satu) kali dalam setahun pada saat hari raya Idul Fitri. c.    Bagi pekerja yang telah bekerja 1 (satu) bulan atau lebih dan kurang dari 12 (dua belas) bulan, besarnya THR yang diberikan dihitung secara proporsional. d.    Besaran THR yang diberikan adalah 1 (satu) bulan upah',
                'jenis_kode' => 'Biaya',
                'kategori' => 'SDM',
            ],
            [
                'kode' => 106,
                'nama_transaksi' => 'BIAYA PEKERJA : TUNJANGAN PERUMAHAN PEKERJA',
                'desc' => 'a.    Tunjangan Perumahan adalah tunjangan yang diberikan kepada pekerja, tidak berdasarkan kehadiran. b.    Besarnya tunjangan perumahan akan ditentukan oleh Perusahaan.',
                'jenis_kode' => 'Biaya',
                'kategori' => 'SDM',
            ],
            [
                'kode' => 107,
                'nama_transaksi' => 'BIAYA PEKERJA : TUNJANGAN FUNGSIONAL',
                'desc' => 'Merupakan tunjangan yang diberikan dengan dasar pertimbangan pada keterampilan dan keahliannya biasanya dibuktikan dengan adanya sertifikasi yang dimilikinya. Misalnya, seperti apoteker, dokter, peneliti, analisis, guru, auditor, dan berbagai pekerjaan lain yang membutuhkan keahlian khusus.',
                'jenis_kode' => 'Biaya',
                'kategori' => 'SDM',
            ],
            [
                'kode' => 108,
                'nama_transaksi' => 'BIAYA PEKERJA : TUNJANGAN RADIASI',
                'desc' => 'a.    Tunjangan Bahaya Radiasi diberikan kepada tenaga profesi yang telah memperoleh “Thermoluminescent Dosimeter Badge” yang dikeluarkan oleh Badan atau Lembaga Pemerintah yang berwenang. b.    Pekerja yang mendapat tunjangan radiasi dimaksud adalah yang melakukan pekerjaan sebagai berikut : 1.   Petugas Proteksi Radiasi (PPR). 2.    Radiologi/Radiographer. 3.     Operator Alat Radiasi. c.    Tingkat Radiasi di atas termasuk tingkat II maka kepada pekerja diberikan tunjangan radiasi tingkat II sesuai Surat Keputusan Direksi yang mengacu pada peraturan yang berlaku.',
                'jenis_kode' => 'Biaya',
                'kategori' => 'SDM',
            ],
            [
                'kode' => 109,
                'nama_transaksi' => 'BIAYA PEKERJA : TUNJANGAN DOKTER JAGA RUANGAN',
                'desc' => 'Tunjangan kepada staf dokter di instalasi rawat inap yang melakukan pengelolaan pelayanan kedokteran baik kedokteran gawat darurat ataupun pelayanan non gawat darurat menggantikan peran Dokter Penanggungjawab pelayanan (DPJP) saat tidak di rumah sakit.',
                'jenis_kode' => 'Biaya',
                'kategori' => 'SDM',
            ],
            [
                'kode' => 110,
                'nama_transaksi' => 'BIAYA PEKERJA : TUNJANGAN TRANSPORT',
                'desc' => 'a.    Tunjangan transport adalah tunjangan yang diberikan kepada pekerja yang besarannya ditentukan oleh Perusahaan. b.    Ketentuan ini berlaku bagi seluruh pekerja.',
                'jenis_kode' => 'Biaya',
                'kategori' => 'SDM',
            ],
            [
                'kode' => 111,
                'nama_transaksi' => 'BIAYA PEKERJA : TUNJANGAN KASIR',
                'desc' => 'Tunjangan atau kompensasi non-gaji yang diberikan kepada karyawan yang bertugas sebagai kasir selain dari gaji pokok.',
                'jenis_kode' => 'Biaya',
                'kategori' => 'SDM',
            ],
            [
                'kode' => 112,
                'nama_transaksi' => 'BIAYA PEKERJA : TUNJANGAN PAJAK PENGHASILAN',
                'desc' => 'Semua pajak yang dikenakan atas penghasilan yang diterima pekerja di Perusahaan menjadi kewajiban pekerja, dan kepada pekerja diberikan tunjangan pajak penghasilan yang besarnya sama dengan pajak penghasilan pekerja serta langsung dibayarkan ke kantor pajak oleh Perusahaan.',
                'jenis_kode' => 'Biaya',
                'kategori' => 'SDM',
            ],
            [
                'kode' => 113,
                'nama_transaksi' => 'BIAYA PEKERJA : HONOR DOKTER',
                'desc' => 'Merupakan  imbalan jasa yang dibayar kepada dokter dari pasien yang dirawatnya.',
                'jenis_kode' => 'Biaya',
                'kategori' => 'SDM',
            ],
            [
                'kode' => 114,
                'nama_transaksi' => 'BIAYA PEKERJA : INSENTIF PRAKTER SORE',
                'desc' => 'Merupakan kompensasi atau imbalan jasa kepada pekerja atas tugasnya praktek sore.',
                'jenis_kode' => 'Biaya',
                'kategori' => 'SDM',
            ],
            [
                'kode' => 115,
                'nama_transaksi' => 'BIAYA PEKERJA : IMBALAN JASA PELAYANAN (IJP)',
                'desc' => 'Merupakan imbalan yang diterima oleh pelaksana pelayanan atau tenaga medis atas pelayanan yang diberikan kepada pasien dalam rangka observasi, diagnosis, pengobatan, rehabilitasi medik dan atau pelayanan langsung.',
                'jenis_kode' => 'Biaya',
                'kategori' => 'SDM',
            ],
            [
                'kode' => 116,
                'nama_transaksi' => 'BIAYA PEKERJA : IMBALAN PASKA KERJA ( PESANGON )',
                'desc' => 'Merupakan imbalan yang harus diberikan kepada karyawan ketika karyawan sudah berhenti bekerja.',
                'jenis_kode' => 'Biaya',
                'kategori' => 'SDM',
            ],
            [
                'kode' => 117,
                'nama_transaksi' => 'BIAYA PEKERJA : IURAN BPJS TENAGA KERJA (JAMINAN KECELAKAAN KERJA)',
                'desc' => 'Merupakan sejumlah uang yang dibayarkan secara teratur oleh peserta atau pemberi kerja untuk program jaminan ketenagakerjaan.',
                'jenis_kode' => 'Biaya',
                'kategori' => 'SDM',
            ],
            [
                'kode' => 118,
                'nama_transaksi' => 'BIAYA PEKERJA : IURAN DANA PENSIUN',
                'desc' => 'Merupakan sejumlah uang yang dibayarkan secara teratur oleh peserta atau pemberi kerja untuk program pensiun karyawan.',
                'jenis_kode' => 'Biaya',
                'kategori' => 'SDM',
            ],
            [
                'kode' => 119,
                'nama_transaksi' => 'BIAYA PEKERJA : BANTUAN KEHADIRAN ( HANDKEY )',
                'desc' => '',
                'jenis_kode' => 'Biaya',
                'kategori' => 'SDM',
            ],
            [
                'kode' => 120,
                'nama_transaksi' => 'BIAYA PEKERJA : UANG SHIFT',
                'desc' => '1.      Tunjangan Regu Bergilir (Premi Shift) a.    Premi Shift adalah bentuk kompensasi yang diberikan kepeda pekerja shift karena bekerja dengan waktu kerja yang tidak normal atau tidak beraturan serta melekat selama status pekerja tersebut tetap Shift dan di dalamnya sudah termasuk perhitungan turn over Shift bagi pekerja biasa dan pekerja pimpinan. b.    Besaran Premi Shift diatur dalam Surat Keputusan Direksi . c.    Premi Shift tidak termasuk unsur upah dalam pembayaran Kompensasi Cuti, Bonus, THR dan Uang Masa Pengabdian.',
                'jenis_kode' => 'Biaya',
                'kategori' => 'SDM',
            ],
            [
                'kode' => 121,
                'nama_transaksi' => 'BIAYA PEKERJA : UANG MAKAN / ON CALL',
                'desc' => 'a.    Tunjangan on call adalah tunjangan yang diberikan kepada pekerja yang karena sifat pekerjaannya untuk setiap saat di luar jam kerja/hari libur dapat dipanggil sesuai jadwal untuk melaksanakan tugasnya yang ditetapkan dengan Surat Keputusan Direksi. b.    Tunjangan on call ini diberikan kepada pekerja yang tidak mendapatkan upah lembur',
                'jenis_kode' => 'Biaya',
                'kategori' => 'SDM',
            ],
            [
                'kode' => 122,
                'nama_transaksi' => 'BIAYA PEKERJA : UANG LEMBUR',
                'desc' => 'a.    Upah lembur adalah upah yang dibayarkan kepada pekerja sebagai kompensasi dari kerja lembur yang dilakukan oleh pekerja tersebut. Upah lembur diberikan kepada pekerja yang tidak mendapat tunjangan jabatan dan Tunjangan On Call. b.     Dasar perhitungan upah lembur sesuai dengan peraturan perundangan yang berlaku.',
                'jenis_kode' => 'Biaya',
                'kategori' => 'SDM',
            ],
            [
                'kode' => 123,
                'nama_transaksi' => 'BIAYA PEKERJA : UANG CUTI',
                'desc' => 'Perusahaan memberikan kompensasi cuti tahunan sebesar 1 (satu) bulan upah dan dibayarkan sebelum jatuh tempo cuti pekerja yang bersangkutan.',
                'jenis_kode' => 'Biaya',
                'kategori' => 'SDM',
            ],
            [
                'kode' => 124,
                'nama_transaksi' => 'BIAYA PEKERJA : TABUNGAN KESEHATAN',
                'desc' => 'Merupakan tabungan karyawan untuk rencana kesehatan atau untuk menabung biaya medis. Tabungan tersebut dapat didanai oleh karyawan dan pemberi kerja.',
                'jenis_kode' => 'Biaya',
                'kategori' => 'SDM',
            ],
            [
                'kode' => 125,
                'nama_transaksi' => 'BIAYA PEKERJA : TUNJANGAN LAIN-LAIN',
                'desc' => 'Merupakan komponen di luar pendapatan utama atau gaji yang dibayar oleh perusahaan kepada karyawan selain tunjangan-tunjangan yang ada.',
                'jenis_kode' => 'Biaya',
                'kategori' => 'SDM',
            ],
            [
                'kode' => 126,
                'nama_transaksi' => 'BIAYA PEKERJA : IURAN BPJS KESEHATAN',
                'desc' => 'a.    Perusahaan mengikutsertakan program BPJS Kesehatan kepada pekerja tetap. b.    Perhitungan dasar iuran bulanan BPJS Kesehatan disesuaikan dengan ketentuan BPJS Kesehatan yang berlaku.',
                'jenis_kode' => 'Biaya',
                'kategori' => 'SDM',
            ],
            [
                'kode' => 127,
                'nama_transaksi' => 'Biaya Pekerja : Tunjangan Freelance',
                'desc' => 'freelance, inship, pkl*spesialis radiologi',
                'jenis_kode' => 'Biaya',
                'kategori' => 'SDM',
            ],
            [
                'kode' => 128,
                'nama_transaksi' => 'Biaya Pekerja : Honor Dokter Non Spesialis',
                'desc' => 'non spesialis',
                'jenis_kode' => 'Biaya',
                'kategori' => 'SDM',
            ],
            [
                'kode' => 129,
                'nama_transaksi' => 'BIAYA PEKERJA : IURAN BPJS TENAGA KERJA (JAMINAN PENSIUN)',
                'desc' => '',
                'jenis_kode' => 'Biaya',
                'kategori' => 'SDM',
            ],
            [
                'kode' => 130,
                'nama_transaksi' => 'BIAYA PEKERJA : IURAN BPJS TENAGA KERJA (JAMINAN KEMATIAN)',
                'desc' => 'sebesar 0,3% dari upah peserta per bulan. Iuran ini sepenuhnya ditanggung oleh pemberi kerja, bukan dipotong dari gaji pekerja. JKM memberikan manfaat berupa uang tunai kepada ahli waris jika peserta meninggal dunia bukan karena kecelakaan kerja',
                'jenis_kode' => 'Biaya',
                'kategori' => 'SDM',
            ],
            [
                'kode' => 131,
                'nama_transaksi' => 'BIAYA PEKERJA : IURAN BPJS TENAGA KERJA (JAMINAN HARI TUA)',
                'desc' => 'sebesar 5,7% dari upah bulanan pekerja, Program ini memberikan manfaat berupa uang tunai kepada pekerja ketika memasuki usia pensiun, mengalami cacat total tetap, atau meninggal dunia',
                'jenis_kode' => 'Biaya',
                'kategori' => 'SDM',
            ],
            [
                'kode' => 201,
                'nama_transaksi' => 'BY.OPRASIONAL (MATERIAL ) : OBAT/ ALKES EXPIRED',
                'desc' => 'Biaya Obat dan alat kesehatan (alkes) yang sudah kedaluwarsa (terjadi perubahan kimia dan fisik pada obat) sehingga dapat mengurangi efektivitasnya atau bahkan menimbulkan efek samping yang berbahaya jika digunakan',
                'jenis_kode' => 'Biaya',
                'kategori' => 'PENUNJANG MEDIS',
            ],
            [
                'kode' => 207,
                'nama_transaksi' => 'BY.OPRASIONAL (MATERIAL ) : BAHAN MAKANAN',
                'desc' => 'Biaya dikeluarkan untuk kepentingan layanan kesehatan pasien (bahan makanan) yang terkait kegiatan rawat inap dan MCU',
                'jenis_kode' => 'Biaya',
                'kategori' => 'PENUNJANG MEDIS',
            ],
            [
                'kode' => 208,
                'nama_transaksi' => 'BY.OPRASIONAL (MATERIAL ) : OBAT-OBATAN JADI',
                'desc' => 'Biaya Barang Habis Pakai (BHP) yang digunakan  untuk kepentingan layanan kesehatan pasien  berupa obat-obatan jadi',
                'jenis_kode' => 'Biaya',
                'kategori' => 'PENUNJANG MEDIS',
            ],
            [
                'kode' => 209,
                'nama_transaksi' => 'BY.OPRASIONAL (MATERIAL ) : ALAT KESEHATAN',
                'desc' => 'Biaya Barang Habis Pakai (BHP) yang digunakan untuk kepentingan layanan kesehatan pasien selain dalam bentuk obat-obatan jadi (X-Ray, Kimia Lab, Gas Medis, dll)',
                'jenis_kode' => 'Biaya',
                'kategori' => 'PENUNJANG MEDIS',
            ],
            [
                'kode' => 226,
                'nama_transaksi' => 'BY.OPRASIONAL (MATERIAL ) : BBM BENSIN, SOLAR & PELUMAS',
                'desc' => 'Biaya Bahan Bakar kendaraan operasional',
                'jenis_kode' => 'Biaya',
                'kategori' => 'FASUM',
            ],
            [
                'kode' => 234,
                'nama_transaksi' => 'BY.OPRASIONAL (MATERIAL ) : RUMAH TANGGA KANTOR ( RTK )',
                'desc' => 'BIAYA MATERIAL',
                'jenis_kode' => 'Biaya',
                'kategori' => 'FASUM',
            ],
            [
                'kode' => 235,
                'nama_transaksi' => 'BY.OPRASIONAL (MATERIAL ) : ALAT TULIS KANTOR ( ATK )',
                'desc' => 'BIAYA MATERIAL',
                'jenis_kode' => 'Biaya',
                'kategori' => 'FASUM',
            ],
            [
                'kode' => 301,
                'nama_transaksi' => 'BY.PEMELIHARAAN : GEDUNG & BANGUNAN  (JASA)',
                'desc' => 'biaya tenaga kerja yang diperlukan untuk menjaga , memelihara, memperbaiki  bangunan dan lingkungan sekitar Rumah Sakit agar  tetap berfungsi dengan baik dan dalam kondisi optimal untuk digunakan',
                'jenis_kode' => 'Biaya',
                'kategori' => 'FASUM',
            ],
            [
                'kode' => 316,
                'nama_transaksi' => 'BY.PEMELIHARAAN : GEDUNG & BANGUNAN (MATERIAL)',
                'desc' => 'biaya bahan dan alat yang diperlukan untuk menjaga , memelihara, memperbaiki  bangunan dan lingkungan sekitar Rumah Sakit agar  tetap berfungsi dengan baik dan dalam kondisi optimal untuk digunakan',
                'jenis_kode' => 'Biaya',
                'kategori' => 'FASUM',
            ],
            [
                'kode' => 305,
                'nama_transaksi' => 'BY.PEMELIHARAAN : KOMPUTER  (JASA)',
                'desc' => 'biaya tenaga kerja yang diperlukan untuk menjaga , memelihara, memperbaiki perangkat kerja yang terkait dengan  pengolahan data, pembuatan dokumen, dan pencetakan informasi (Komputer, Printer,dll)
 sekitar Rumah Sakit agar  tetap berfungsi dengan baik dan dalam kondisi optimal untuk digunakan',
                'jenis_kode' => 'Biaya',
                'kategori' => 'FASUM',
            ],
            [
                'kode' => 317,
                'nama_transaksi' => 'BY.PEMELIHARAAN : KOMPUTER  (MATERIAL)',
                'desc' => 'biaya bahan dan alat  yang diperlukan untuk menjaga , memelihara, memperbaiki perangkat kerja yang terkait dengan  pengolahan data, pembuatan dokumen, dan pencetakan informasi (Komputer, Printer,dll)
 sekitar Rumah Sakit agar  tetap berfungsi dengan baik dan dalam kondisi optimal untuk digunakan',
                'jenis_kode' => 'Biaya',
                'kategori' => 'FASUM',
            ],
            [
                'kode' => 308,
                'nama_transaksi' => 'BY.PEMELIHARAAN : PERALATAN UMUM (JASA)',
                'desc' => 'biaya tenaga kerja yang diperlukan untuk menjaga , memelihara, memperbaiki perangkat kerja lainnya selain alat medis dan alat yang terkait pengolahan data, pembuatan dokumen dan pencetakan informasi (Peralatan Elektronik, Kendaraan , dll)
 sekitar Rumah Sakit agar  tetap berfungsi dengan baik dan dalam kondisi optimal untuk digunakan',
                'jenis_kode' => 'Biaya',
                'kategori' => 'FASUM',
            ],
            [
                'kode' => 314,
                'nama_transaksi' => 'BY.PEMELIHARAAN : PERALATAN UMUM (MATERIAL)',
                'desc' => 'biaya bahan dan alat  yang diperlukan untuk menjaga , memelihara, memperbaiki perangkat kerja lainnya selain alat medis dan alat yang terkait pengolahan data, pembuatan dokumen dan pencetakan informasi (Peralatan Elektronik, Kendaraan , dll)
 sekitar Rumah Sakit agar  tetap berfungsi dengan baik dan dalam kondisi optimal untuk digunakan',
                'jenis_kode' => 'Biaya',
                'kategori' => 'FASUM',
            ],
            [
                'kode' => 310,
                'nama_transaksi' => 'BY.PEMELIHARAAN : ALAT MEDIS  (JASA)',
                'desc' => 'biaya tenaga kerja yang diperlukan untuk menjaga , memelihara, memperbaiki perangkat kerja yang terkait dengan  layanan/ kegiatan medis secara langsung maupung tidak langsung',
                'jenis_kode' => 'Biaya',
                'kategori' => 'FASUM',
            ],
            [
                'kode' => 315,
                'nama_transaksi' => 'BY.PEMELIHARAAN : ALAT MEDIS  (MATERIAL)',
                'desc' => 'biaya bahan dan alat  yang diperlukan untuk menjaga , memelihara, memperbaiki perangkat kerja yang terkait dengan  layanan/ kegiatan medis secara langsung maupung tidak langsung',
                'jenis_kode' => 'Biaya',
                'kategori' => 'FASUM',
            ],
            [
                'kode' => 401,
                'nama_transaksi' => 'BY.PENYUSUTAN & AMORTISASI : GEDUNG DAN BANGUNAN',
                'desc' => 'BIAYA PENYUSUTAN & AMORTISASI',
                'jenis_kode' => 'Biaya',
                'kategori' => 'Keuangan',
            ],
            [
                'kode' => 405,
                'nama_transaksi' => 'BY.PENYUSUTAN & AMORTISASI : PERALATAN KANTOR',
                'desc' => 'BIAYA PENYUSUTAN & AMORTISASI',
                'jenis_kode' => 'Biaya',
                'kategori' => 'Keuangan',
            ],
            [
                'kode' => 406,
                'nama_transaksi' => 'BY.PENYUSUTAN & AMORTISASI : KOMPUTER',
                'desc' => 'BIAYA PENYUSUTAN & AMORTISASI',
                'jenis_kode' => 'Biaya',
                'kategori' => 'Keuangan',
            ],
            [
                'kode' => 411,
                'nama_transaksi' => 'BY.PENYUSUTAN & AMORTISASI : ALAT MEDIS',
                'desc' => 'BIAYA PENYUSUTAN & AMORTISASI',
                'jenis_kode' => 'Biaya',
                'kategori' => 'Keuangan',
            ],
            [
                'kode' => 601,
                'nama_transaksi' => 'BY.SEWA  : GEDUNG / LAHAN',
                'desc' => 'BIAYA SEWA / KONTRAK',
                'jenis_kode' => 'Biaya',
                'kategori' => 'Legal',
            ],
            [
                'kode' => 602,
                'nama_transaksi' => 'BY.SEWA  :  KENDARAAN',
                'desc' => 'BIAYA SEWA / KONTRAK',
                'jenis_kode' => 'Biaya',
                'kategori' => 'Legal',
            ],
            [
                'kode' => 603,
                'nama_transaksi' => 'BY.SEWA  :  KOMPUTER & PERLENGKAPANNYA',
                'desc' => 'BIAYA SEWA / KONTRAK',
                'jenis_kode' => 'Biaya',
                'kategori' => 'Legal',
            ],
            [
                'kode' => 604,
                'nama_transaksi' => 'BY.SEWA  :  ALAT KESEHATAN',
                'desc' => 'BIAYA SEWA / KONTRAK',
                'jenis_kode' => 'Biaya',
                'kategori' => 'Legal',
            ],
            [
                'kode' => 609,
                'nama_transaksi' => 'BY.SEWA  :  RUMAH TANGGA KANTOR ( RTK )',
                'desc' => 'BIAYA SEWA / KONTRAK',
                'jenis_kode' => 'Biaya',
                'kategori' => 'Legal',
            ],
            [
                'kode' => 614,
                'nama_transaksi' => 'BY. KONTRAK  : KEBERSIHAN',
                'desc' => 'BIAYA SEWA / KONTRAK',
                'jenis_kode' => 'Biaya',
                'kategori' => null,
            ],
            [
                'kode' => 618,
                'nama_transaksi' => 'BY. KONTRAK  : KONTRAK KERJA SAMA LAYANAN KESEHATAN',
                'desc' => 'BIAYA SEWA / KONTRAK',
                'jenis_kode' => 'Biaya',
                'kategori' => null,
            ],
            [
                'kode' => 623,
                'nama_transaksi' => 'BY. KONTRAK  : KERJASAMA (KSO / KBH )',
                'desc' => 'BIAYA SEWA / KONTRAK',
                'jenis_kode' => 'Biaya',
                'kategori' => null,
            ],
            [
                'kode' => 624,
                'nama_transaksi' => 'BY. KONTRAK  : KONSULTAN',
                'desc' => 'BIAYA SEWA / KONTRAK',
                'jenis_kode' => 'Biaya',
                'kategori' => null,
            ],
            [
                'kode' => 701,
                'nama_transaksi' => 'ADMINISTRASI KTR : POS, MATERAI,PERANGKO, TELEX, IURAN TV',
                'desc' => 'BIAYA ADMINISTRASI & UMUM',
                'jenis_kode' => 'Biaya',
                'kategori' => null,
            ],
            [
                'kode' => 702,
                'nama_transaksi' => 'ADMINISTRASI KTR : BIAYA KEUANGAN ( PREMI, DLL )',
                'desc' => 'BIAYA ADMINISTRASI & UMUM',
                'jenis_kode' => 'Biaya',
                'kategori' => null,
            ],
            [
                'kode' => 703,
                'nama_transaksi' => 'ADMINISTRASI KTR : PERIJINAN, DOKUMENTASI, RAPAT  DLL',
                'desc' => 'biaya terkait untuk mendapatkan surat ijin kegiatan operasional rumah sakit yang meliputI ijin layanan dan ijin penggunaan barang (ijin akreditasi, kalibrasi alat, badge pekerja, sertifikat keselamatan dan kesehatan kerja)',
                'jenis_kode' => 'Biaya',
                'kategori' => null,
            ],
            [
                'kode' => 804,
                'nama_transaksi' => 'BIAYA UMUM  : FAMILY GATHERING',
                'desc' => 'biaya terkait kegiatan kebersamaan internal SDM rumah sakit yang meliputi acara duka maupun sukacita',
                'jenis_kode' => 'Biaya',
                'kategori' => null,
            ],
            [
                'kode' => 807,
                'nama_transaksi' => 'BIAYA UMUM : BAGIAN UMUM',
                'desc' => 'BIAYA ADMINISTRASI & UMUM',
                'jenis_kode' => 'Biaya',
                'kategori' => null,
            ],
            [
                'kode' => 810,
                'nama_transaksi' => 'BIAYA UMUM : SPONSORSHIP & CSR',
                'desc' => 'biaya terkait dengan pihak ekserternal SDM rumah sakit yang bertujuan  untuk meningkatkan promosi dan pemasaran layanan yang dilakukan melalui dukungan finansial atau sumber daya lainnya',
                'jenis_kode' => 'Biaya',
                'kategori' => null,
            ],
            [
                'kode' => 812,
                'nama_transaksi' => 'BIAYA UMUM : PERJALANAN DINAS (UANG HARIAN)',
                'desc' => 'BIAYA ADMINISTRASI & UMUM',
                'jenis_kode' => 'Biaya',
                'kategori' => null,
            ],
            [
                'kode' => 813,
                'nama_transaksi' => 'BIAYA UMUM : PENDIDIKAN ( SIMPOSIUM/TRAINING/KURSUS )',
                'desc' => 'BIAYA ADMINISTRASI & UMUM',
                'jenis_kode' => 'Biaya',
                'kategori' => null,
            ],
            [
                'kode' => 814,
                'nama_transaksi' => 'BIAYA UMUM : PAKAIAN DINAS',
                'desc' => 'BIAYA ADMINISTRASI & UMUM',
                'jenis_kode' => 'Biaya',
                'kategori' => null,
            ],
            [
                'kode' => 818,
                'nama_transaksi' => 'BIAYA UMUM : PERJALANAN DINAS (TIKET PERJALANAN)',
                'desc' => 'BIAYA ADMINISTRASI & UMUM',
                'jenis_kode' => 'Biaya',
                'kategori' => null,
            ],
            [
                'kode' => 820,
                'nama_transaksi' => 'BIAYA UMUM : LISTRIK ( PLN )',
                'desc' => 'BIAYA ADMINISTRASI & UMUM',
                'jenis_kode' => 'Biaya',
                'kategori' => null,
            ],
            [
                'kode' => 821,
                'nama_transaksi' => 'BIAYA UMUM : AIR ( PAM )',
                'desc' => 'BIAYA ADMINISTRASI & UMUM',
                'jenis_kode' => 'Biaya',
                'kategori' => null,
            ],
            [
                'kode' => 822,
                'nama_transaksi' => 'BIAYA UMUM : PULSA TELEPONE',
                'desc' => 'BIAYA ADMINISTRASI & UMUM',
                'jenis_kode' => 'Biaya',
                'kategori' => null,
            ],
            [
                'kode' => 824,
                'nama_transaksi' => 'BIAYA UMUM : BIAYA BANK',
                'desc' => 'BIAYA ADMINISTRASI & UMUM',
                'jenis_kode' => 'Biaya',
                'kategori' => null,
            ],
            [
                'kode' => 826,
                'nama_transaksi' => 'BIAYA UMUM : PAJAK JASA GIRO',
                'desc' => 'BIAYA ADMINISTRASI & UMUM',
                'jenis_kode' => 'Biaya',
                'kategori' => null,
            ],
            [
                'kode' => 830,
                'nama_transaksi' => 'BIAYA UMUM : PERJALANAN DINAS (PENGINAPAN)',
                'desc' => 'BIAYA ADMINISTRASI & UMUM',
                'jenis_kode' => 'Biaya',
                'kategori' => null,
            ],
            [
                'kode' => 835,
                'nama_transaksi' => 'BIAYA UMUM : BIAYA PAJAK (PPN)',
                'desc' => 'BIAYA ADMINISTRASI & UMUM',
                'jenis_kode' => 'Biaya',
                'kategori' => null,
            ],
            [
                'kode' => 836,
                'nama_transaksi' => 'BIAYA UMUM : PAJAK TANGGUHAN',
                'desc' => 'BIAYA ADMINISTRASI & UMUM',
                'jenis_kode' => 'Biaya',
                'kategori' => null,
            ],
            [
                'kode' => 837,
                'nama_transaksi' => 'BIAYA UMUM : BIAYA PAJAK (SANKSI ADMINISTRASI)',
                'desc' => 'BIAYA ADMINISTRASI & UMUM',
                'jenis_kode' => 'Biaya',
                'kategori' => null,
            ],
            [
                'kode' => 838,
                'nama_transaksi' => 'BIAYA UMUM : PBB ( PAJAK BUMI & BANGUNAN )',
                'desc' => 'BIAYA ADMINISTRASI & UMUM',
                'jenis_kode' => 'Biaya',
                'kategori' => null,
            ],
            [
                'kode' => 841,
                'nama_transaksi' => 'BIAYA UMUM : TRANSPORT ( TOL, PARKIR DLL )',
                'desc' => 'BIAYA ADMINISTRASI & UMUM',
                'jenis_kode' => 'Biaya',
                'kategori' => null,
            ],
            [
                'kode' => 842,
                'nama_transaksi' => 'BIAYA UMUM : BIAYA PAJAK (BADAN)',
                'desc' => 'BIAYA ADMINISTRASI & UMUM',
                'jenis_kode' => 'Biaya',
                'kategori' => null,
            ],
            [
                'kode' => 843,
                'nama_transaksi' => 'BIAYA UMUM : BIAYA PAJAK (KURANG BAYAR TAHUN LALU)',
                'desc' => 'BIAYA ADMINISTRASI & UMUM',
                'jenis_kode' => 'Biaya',
                'kategori' => null,
            ],
            [
                'kode' => 844,
                'nama_transaksi' => 'BIAYA UMUM : PERJALANAN TRAINING (UANG HARIAN)',
                'desc' => 'BIAYA ADMINISTRASI & UMUM',
                'jenis_kode' => 'Biaya',
                'kategori' => null,
            ],
            [
                'kode' => 845,
                'nama_transaksi' => 'BIAYA UMUM : PERJALANAN TRAINING (TIKET PERJALANAN)',
                'desc' => 'BIAYA ADMINISTRASI & UMUM',
                'jenis_kode' => 'Biaya',
                'kategori' => null,
            ],
            [
                'kode' => 846,
                'nama_transaksi' => 'BIAYA UMUM : PERJALANAN TRAINING (PENGINAPAN)',
                'desc' => 'BIAYA ADMINISTRASI & UMUM',
                'jenis_kode' => 'Biaya',
                'kategori' => null,
            ],
        ];

        $kode_pendapatan = [
            [
                'kode' => '020',
                'nama_transaksi' => 'Pendapatan Rawat Jalan : Pendapatan Kapitasi Prokespen',
                'desc' => 'Penerimaan dana flat/tetap di muka setiap bulan per jiwa untuk menjamin kesehatan peserta pensiunan. (Dana kapitasi bulanan Pensiunan Pertamina, Dana tetap bulanan Pensiunan PLN)',
                'jenis_kode' => 'Pendapatan',
            ],
            [
                'kode' => '040',
                'nama_transaksi' => 'Pendapatan Rawat Jalan : Pendapatan Kapitasi  Bpjs',
                'desc' => 'Dana pra-upaya bulanan dari BPJS Kesehatan berdasarkan jumlah peserta jaminan yang terikat di faskes primer RS. (Dana kapitasi bulanan dari BPJS Kesehatan untuk klinik satelit/FKTP milik RS)',
                'jenis_kode' => 'Pendapatan',
            ],
            [
                'kode' => '110',
                'nama_transaksi' => 'Pendapatan Rawat Jalan : Konsul Rawat Jalan',
                'desc' => 'Jasa pemeriksaan, diagnosis, dan konsultasi tatap muka oleh dokter spesialis atau dokter umum di area poliklinik. (Jasa Periksa Dokter Spesialis Penyakit Dalam, Jasa Periksa Dokter Spesialis Mata, Konsultasi Dokter Umum Klinik Perusahaan, Jasa Periksa Dokter Spesialis Jantung)',
                'jenis_kode' => 'Pendapatan',
            ],
            [
                'kode' => '130',
                'nama_transaksi' => 'Pendapatan Rawat Jalan : Tindakan Rawat Jalan',
                'desc' => 'Pendapatan dari prosedur medis, intervensi klinis, atau bedah minor yang selesai di hari yang sama tanpa menginap. (Injeksi/Suntik Vitamin Neurobion (Pensiunan), Nebulizer/Terapi Uap, Fisioterapi (Terapi Infra Red & Diathermy), Rawat luka diabetes, Rekam Jantung (EKG), Pencabutan gigi)',
                'jenis_kode' => 'Pendapatan',
            ],
            [
                'kode' => '920',
                'nama_transaksi' => 'Pendapatan Rawat Jalan : Extra Fooding',
                'desc' => 'Penyediaan makanan, snack, atau nutrisi tambahan khusus di luar standar klinis dasar untuk pasien rawat jalan tertentu. (Pemberian susu khusus Lansia (Ensure/Entrasol), Snack box pasien hemodialisa, Makanan tambahan diet rendah garam untuk pasien jantung)',
                'jenis_kode' => 'Pendapatan',
            ],
            [
                'kode' => '620',
                'nama_transaksi' => 'Pendapatan Rawat Jalan : Ambulance R-Jalan',
                'desc' => 'Biaya sewa mobil ambulans beserta tim medis untuk penjemputan, pengantaran, atau siaga pasien non-opname. (Antar jemput pasien lansia untuk cuci darah, Penjemputan karyawan sakit di lokasi pabrik/kantor mitra, Ambulans siaga untuk event perusahaan)',
                'jenis_kode' => 'Pendapatan',
            ],
            [
                'kode' => '340',
                'nama_transaksi' => 'Pendapatan Rawat Jalan : M  C  U',
                'desc' => 'Pendapatan dari paket pemeriksaan kesehatan menyeluruh (Medical Check Up) baik untuk individu maupun instansi. (Paket MCU Karyawan Baru (Pre-employment), Paket MCU Tahunan Perusahaan (Annual MCU), Paket MCU Pensiunan Sehat, Tes Narkoba & Alkohol Karyawan)',
                'jenis_kode' => 'Pendapatan',
            ],
            [
                'kode' => '111',
                'nama_transaksi' => 'Pendapatan Rawat Inap : Konsul Rawat Inap',
                'desc' => 'Jasa kunjungan (visite) harian atau konsultasi antar-spesialis (joint care) dokter kepada pasien yang sedang diopname. (Visite harian Dokter Jantung (DPJP), Visite Dokter Spesialis Paru, Konsultasi bersama Dokter Bedah dan Dokter Penyakit Dalam di bangsal)',
                'jenis_kode' => 'Pendapatan',
            ],
            [
                'kode' => '131',
                'nama_transaksi' => 'Pendapatan Rawat Inap : Tindakan Rawat Inap',
                'desc' => 'Segala prosedur medis, keperawatan, atau tindakan bedah besar/kecil selama pasien menempati kamar perawatan. (Operasi Katarak (Banyak pada Pensiunan), Operasi Usus Buntu, Pasang Selang Infus, Pasang Kateter Urin, Pemasangan Oksigen (O2) per jam, Tindakan Cuci Darah (Hemodialisa))',
                'jenis_kode' => 'Pendapatan',
            ],
            [
                'kode' => '210',
                'nama_transaksi' => 'Pendapatan Rawat Inap : Sewa Kamar Perawatan',
                'desc' => 'Biaya akomodasi penggunaan fasilitas kamar dan tempat tidur perawatan dihitung per hari berdasarkan kelas kamar. (Sewa Kamar VIP (Jaminan Perusahaan), Sewa Kamar Kelas 1 (BPJS/Pensiunan), Sewa Kamar Kelas 2, Kamar ICU/ICCU (Intensif))',
                'jenis_kode' => 'Pendapatan',
            ],
            [
                'kode' => '621',
                'nama_transaksi' => 'Pendapatan Rawat Inap : Ambulance R-Inap',
                'desc' => 'Biaya sewa ambulans khusus untuk mobilisasi pasien rawat inap (rujukan antar-RS atau pemulangan pasien pasca-opname). (Merujuk pasien stroke kritis ke RS tipe pusat, Antar pulang jenazah pasien ke rumah duka, Transportasi evakuasi medis darurat antar-RS)',
                'jenis_kode' => 'Pendapatan',
            ],
            [
                'kode' => '710',
                'nama_transaksi' => 'Pendapatan Penunjang Medis : Radioterapi R-Jalan',
                'desc' => 'Layanan terapi radiasi (sinar) pengion untuk pengobatan kanker bagi pasien luar yang datang terjadwal (tanpa menginap). (Sesi Terapi Sinar/Radiasi Kanker Prostat (Lansia), Sesi Radioterapi Kanker Payudara (Pasien luar/rujukan))',
                'jenis_kode' => 'Pendapatan',
            ],
            [
                'kode' => '711',
                'nama_transaksi' => 'Pendapatan Penunjang Medis : Radioterapi R-Inap',
                'desc' => 'Layanan terapi radiasi (sinar) untuk pengobatan kanker yang diberikan kepada pasien yang sedang dirawat inap. (Tindakan Brakiterapi (radiasi internal), Sesi radioterapi terjadwal untuk pasien tumor otak yang sedang opname)',
                'jenis_kode' => 'Pendapatan',
            ],
            [
                'kode' => '810',
                'nama_transaksi' => 'Pendapatan Penunjang Medis : Laboratorium R-Jalan',
                'desc' => 'Pendapatan dari pengujian spesimen cairan/jaringan biologis tubuh untuk penegakan diagnosis pasien poliklinik. (Cek Gula Darah Puasa, Cek Asam Urat & Kolesterol, Tes fungsi ginjal (Ureum/Kreatinin), Tes fungsi hati (SGOT/SGPT), Pemeriksaan HBA1c (Kontrol Diabetes))',
                'jenis_kode' => 'Pendapatan',
            ],
            [
                'kode' => '811',
                'nama_transaksi' => 'Pendapatan Penunjang Medis : Laboratorium R-Inap',
                'desc' => 'Pendapatan dari pengujian spesimen biologis tubuh untuk memantau perkembangan kondisi pasien opname/kritis. (Cek Elektrolit (Kalium/Natrium/Klorida) harian, Analisa Gas Darah (AGD) di ICU, Tes Kultur Urin & resistensi antibiotik, Cek Darah Lengkap serial)',
                'jenis_kode' => 'Pendapatan',
            ],
            [
                'kode' => '910',
                'nama_transaksi' => 'Pendapatan Penunjang Medis : Administrasi Medis R-Jalan',
                'desc' => 'Biaya pengelolaan berkas rekam medis, pendaftaran loket, cetak kartu, dan validasi asuransi komersil/korporat pasien luar. (Biaya pendaftaran pasien baru, Biaya cetak Kartu Berobat/Barcode, Biaya administrasi gesek kartu asuransi korporat (AdMedika/MDS))',
                'jenis_kode' => 'Pendapatan',
            ],
            [
                'kode' => '911',
                'nama_transaksi' => 'Pendapatan Penunjang Medis : Administrasi Medis R-Inap',
                'desc' => 'Biaya pemberkasan administrasi, resume medis, dan proses kelengkapan dokumen pemulangan (discharge) pasien opname. (Biaya fotokopi legalisir berkas rekam medis untuk klaim, Biaya pembuatan Resume Medis pengajuan asuransi, Biaya administrasi pemulangan (Discharge fee))',
                'jenis_kode' => 'Pendapatan',
            ],
            [
                'kode' => '420',
                'nama_transaksi' => 'Pendapatan Farmasi : Obat Farmasi R-Jalan',
                'desc' => 'Pendapatan dari penjualan obat-obatan resmi (paten, generik, racikan) berdasarkan resep dokter poliklinik. (Obat Diabetes (Metformin, Glimepiride), Obat Hipertensi (Amlodipine, Candesartan), Obat Kolesterol (Atorvastatin), Obat Jantung (ISDN), Insulin Pen)',
                'jenis_kode' => 'Pendapatan',
            ],
            [
                'kode' => '421',
                'nama_transaksi' => 'Pendapatan Farmasi : Obat Farmasi R-Inap',
                'desc' => 'Pendapatan dari sediaan obat-obatan, cairan injeksi, atau infus yang dideposisikan khusus ke kamar rawat inap pasien. (Cairan Infus (Aringer Lactate, NaCl), Antibiotik Injeksi (Ceftriaxone, Meropenem), Obat Nyeri Injeksi (Ketorolac), Obat Maag Suntik (Omeprazole vial))',
                'jenis_kode' => 'Pendapatan',
            ],
            [
                'kode' => '520',
                'nama_transaksi' => 'Pendapatan Farmasi : Alat Kesehatan Non Resep R-Jalan',
                'desc' => 'Pendapatan penjualan retail Alat Kesehatan Habis Pakai (AKHP) atau alat bantu fisik yang dibeli mandiri oleh pasien rawat jalan. (Alat bantu jalan (Kruk/Tongkat Kaki 4), Korset Lumbal (Sakit Pinggang Lansia), Alat cek gula darah mandiri (Glukometer), Masker Medis, Popok Dewasa (Diapers))',
                'jenis_kode' => 'Pendapatan',
            ],
            [
                'kode' => '521',
                'nama_transaksi' => 'Pendapatan Farmasi : Alat Kesehatan Non Resep R-Inap',
                'desc' => 'Pemakaian Alat Kesehatan Habis Pakai (AKHP) atau BMHP medis yang dibebankan langsung pada billing perawatan pasien opname. (Selang Infus (Infusion Set), Jarum Infus (Abocath), Selang Oksigen (Nasal Canula), Plester gulung, Kassa Steril, Gel USG/EKG, Syringe Disposable (Spet))',
                'jenis_kode' => 'Pendapatan',
            ],
            [
                'kode' => '951',
                'nama_transaksi' => 'Pendapatan Umum : Jasa Giro',
                'desc' => 'Pendapatan non-operasional berupa bunga atau bagi hasil atas penempatan dana operasional RS di rekening koran/giro bank. (Pendapatan bunga tabungan Giro operasional RS di Bank Mandiri, BNI, atau BRI)',
                'jenis_kode' => 'Pendapatan',
            ],
            [
                'kode' => '970',
                'nama_transaksi' => 'Pendapatan Umum : Discount',
                'desc' => 'Akun pengurang pendapatan (kontra-akun) atas pemotongan harga resmi yang disetujui manajemen untuk pihak tertentu. (Potongan harga Paket MCU khusus HUT Perusahaan Mitra, Diskon biaya obat/kamar atas kebijakan Direktur RS)',
                'jenis_kode' => 'Pendapatan',
            ],
            [
                'kode' => '991',
                'nama_transaksi' => 'Pendapatan Umum : Selisih Pendapatan Layanan Bpjs (Ina-Cbgs)',
                'desc' => 'Akun rekonsiliasi selisih antara akumulasi total tarif riil rumah sakit dengan nominal klaim paket INA-CBGs yang dibayar BPJS. (Penyesuaian selisih billing RS Rp10 Juta vs Nilai Paket INA-CBGs yang dibayar BPJS Rp8.5 Juta (Selisih dicatat di pos ini))',
                'jenis_kode' => 'Pendapatan',
            ],
            [
                'kode' => '992',
                'nama_transaksi' => 'Pendapatan Umum : Selisih Pendapatan Layanan Mandiri Inhealth (Telaah)',
                'desc' => 'Akun koreksi pendapatan atas klaim Mandiri Inhealth pasca-proses review medis atau telaah dari verifikator asuransi. (Pemotongan nilai klaim oleh verifikator Inhealth karena ketidaksesuaian berkas atau indikasi diagnosis medis)',
                'jenis_kode' => 'Pendapatan',
            ],
            [
                'kode' => '993',
                'nama_transaksi' => 'Pendapatan Umum : Selisih Pendapatan Layanan Mandiri Inhealth (Tarif)',
                'desc' => 'Akun untuk menampung selisih nominal akibat perbedaan tarif komersial RS dengan plafon kontrak asuransi Mandiri Inhealth. (Selisih tarif kamar komersial RS Kelas 1 sebesar Rp500.000 vs jaminan plafon Inhealth yang hanya menyetujui Rp400.000)',
                'jenis_kode' => 'Pendapatan',
            ],
            [
                'kode' => '994',
                'nama_transaksi' => 'Pendapatan Umum : Selisih Pendapatan Layanan Pisa Pt Badak',
                'desc' => 'Akun rekonsiliasi penyesuaian khusus untuk mencatat perbedaan tagihan RS dengan batas pagu (ceiling) tahunan pekerja PT Badak (PISA). (Penyesuaian nilai tagihan obat non-formularium jaminan PISA PT Badak yang tidak lolos verifikasi pertanggungan penuh perusahaan)',
                'jenis_kode' => 'Pendapatan',
            ],
            [
                'kode' => '995',
                'nama_transaksi' => 'Pendapatan Umum : Selisih Pendapatan Layanan Jaminan Lainnya',
                'desc' => 'Wadah pencatatan selisih biaya penjamin korporasi atau asuransi swasta luar lainnya akibat batas plafon (excess claim). (Selisih kelebihan biaya (excess claim) asuransi karyawan perusahaan (seperti Yakes Telkom, Astra, Chevron, Allianz))',
                'jenis_kode' => 'Pendapatan',
            ],
            [
                'kode' => '999',
                'nama_transaksi' => 'Pendapatan Umum : Lain - Lain',
                'desc' => 'Tempat penampungan seluruh pendapatan incidental/tak terduga yang tidak masuk kualifikasi logis pos akun medis mana pun. (Pendapatan sewa kantin RS, Sewa ruang mesin ATM, Hasil penjualan limbah jerigen kosong cuci darah/farmasi, Biaya parkir pengunjung)',
                'jenis_kode' => 'Pendapatan',
            ],
        ];


        foreach ($kode_biaya as $kode) {
            KodeTransaksi::create($kode);
        }

        foreach ($kode_pendapatan as $kode) {
            KodeTransaksi::create($kode);
        }
    }
}
