<?php

namespace Database\Seeders;

use App\Models\Unit;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class UnitSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $units = [
            [
                'nama' => 'IGD',
                'kode_pendapatan' => '701.09',
                'desc_pendapatan' => 'PENDAPATAN RAWAT JALAN-IGD',
                'kode_biaya' => '801.09',
                'desc_biaya' => 'BIAYA RAWAT JALAN-IGD',
            ],
            [
                'nama' => 'POLI UMUM',
                'kode_pendapatan' => '701.22',
                'desc_pendapatan' => 'PENDAPATAN RAWAT JALAN-POLI UMUM',
                'kode_biaya' => '801.22',
                'desc_biaya' => 'BIAYA RAWAT JALAN-POLI UMUM',
            ],
            [
                'nama' => 'POLI SPECIALIS REHABILITASI MEDIK',
                'kode_pendapatan' => '701.23',
                'desc_pendapatan' => 'PENDAPATAN RAWAT JALAN-POLI SPECIALIS REHABILITASI MEDIK',
                'kode_biaya' => '801.23',
                'desc_biaya' => 'BIAYA RAWAT JALAN-POLI SPECIALIS REHABILITASI MEDIK',
            ],
            [
                'nama' => 'POLI SPECIALIS ORTODONTI',
                'kode_pendapatan' => '701.24',
                'desc_pendapatan' => 'PENDAPATAN RAWAT JALAN-POLI SPECIALIS ORTODONTI',
                'kode_biaya' => '801.24',
                'desc_biaya' => 'BIAYA RAWAT JALAN-POLI SPECIALIS ORTODONTI',
            ],
            [
                'nama' => 'POLI SPECIALIS PERIODONSIA',
                'kode_pendapatan' => '701.25',
                'desc_pendapatan' => 'PENDAPATAN RAWAT JALAN-POLI SPECIALIS PERIODONSIA',
                'kode_biaya' => '801.25',
                'desc_biaya' => 'BIAYA RAWAT JALAN-POLI SPECIALIS PERIODONSIA',
            ],
            [
                'nama' => 'POLI SPECIALIS PROSTODONTI',
                'kode_pendapatan' => '701.14',
                'desc_pendapatan' => 'PENDAPATAN RAWAT JALAN-POLI SPECIALIS PROSTODONTI',
                'kode_biaya' => '801.14',
                'desc_biaya' => 'BIAYA RAWAT JALAN-POLI SPECIALIS PROSTODONTI',
            ],
            [
                'nama' => 'BKIA',
                'kode_pendapatan' => '701.29',
                'desc_pendapatan' => 'PENDAPATAN RAWAT JALAN-BKIA',
                'kode_biaya' => '801.29',
                'desc_biaya' => 'BIAYA RAWAT JALAN-BKIA',
            ],
            [
                'nama' => 'PDP HIV',
                'kode_pendapatan' => '701.30',
                'desc_pendapatan' => 'PENDAPATAN RAWAT JALAN-PDP HIV',
                'kode_biaya' => '801.30',
                'desc_biaya' => 'BIAYA RAWAT JALAN-PDP HIV',
            ],
            [
                'nama' => 'POLI SPECIALIS BEDAH UMUM',
                'kode_pendapatan' => '701.32',
                'desc_pendapatan' => 'PENDAPATAN RAWAT JALAN-POLI SPECIALIS BEDAH UMUM',
                'kode_biaya' => '801.32',
                'desc_biaya' => 'BIAYA RAWAT JALAN-POLI SPECIALIS BEDAH UMUM',
            ],
            [
                'nama' => 'POLI SPECIALIS THT',
                'kode_pendapatan' => '701.33',
                'desc_pendapatan' => 'PENDAPATAN RAWAT JALAN-POLI SPECIALIS THT',
                'kode_biaya' => '801.33',
                'desc_biaya' => 'BIAYA RAWAT JALAN-POLI SPECIALIS THT',
            ],
            [
                'nama' => 'POLI SPECIALIS PENYAKIT DALAM',
                'kode_pendapatan' => '701.34',
                'desc_pendapatan' => 'PENDAPATAN RAWAT JALAN-POLI SPECIALIS PENYAKIT DALAM',
                'kode_biaya' => '801.34',
                'desc_biaya' => 'BIAYA RAWAT JALAN-POLI SPECIALIS PENYAKIT DALAM',
            ],
            [
                'nama' => 'POLI SPECIALIS JANTUNG',
                'kode_pendapatan' => '701.35',
                'desc_pendapatan' => 'PENDAPATAN RAWAT JALAN-POLI SPECIALIS JANTUNG',
                'kode_biaya' => '801.35',
                'desc_biaya' => 'BIAYA RAWAT JALAN-POLI SPECIALIS JANTUNG',
            ],
            [
                'nama' => 'POLI SPECIALIS ANAK',
                'kode_pendapatan' => '701.36',
                'desc_pendapatan' => 'PENDAPATAN RAWAT JALAN-POLI SPECIALIS ANAK',
                'kode_biaya' => '801.36',
                'desc_biaya' => 'BIAYA RAWAT JALAN-POLI SPECIALIS ANAK',
            ],
            [
                'nama' => 'POLI SPECIALIS MATA',
                'kode_pendapatan' => '701.37',
                'desc_pendapatan' => 'PENDAPATAN RAWAT JALAN-POLI SPECIALIS MATA',
                'kode_biaya' => '801.37',
                'desc_biaya' => 'BIAYA RAWAT JALAN-POLI SPECIALIS MATA',
            ],
            [
                'nama' => 'POLI SPECIALIS KEBIDANAN',
                'kode_pendapatan' => '701.38',
                'desc_pendapatan' => 'PENDAPATAN RAWAT JALAN-POLI SPECIALIS KEBIDANAN',
                'kode_biaya' => '801.38',
                'desc_biaya' => 'BIAYA RAWAT JALAN-POLI SPECIALIS KEBIDANAN',
            ],
            [
                'nama' => 'POLI SPECIALIS SYARAF',
                'kode_pendapatan' => '701.39',
                'desc_pendapatan' => 'PENDAPATAN RAWAT JALAN-POLI SPECIALIS SYARAF',
                'kode_biaya' => '801.39',
                'desc_biaya' => 'BIAYA RAWAT JALAN-POLI SPECIALIS SYARAF',
            ],
            [
                'nama' => 'POLI SPECIALIS JIWA',
                'kode_pendapatan' => '701.40',
                'desc_pendapatan' => 'PENDAPATAN RAWAT JALAN-POLI SPECIALIS JIWA',
                'kode_biaya' => '801.40',
                'desc_biaya' => 'BIAYA RAWAT JALAN-POLI SPECIALIS JIWA',
            ],
            [
                'nama' => 'POLI SPECIALIS KULIT',
                'kode_pendapatan' => '701.41',
                'desc_pendapatan' => 'PENDAPATAN RAWAT JALAN-POLI SPECIALIS KULIT',
                'kode_biaya' => '801.41',
                'desc_biaya' => 'BIAYA RAWAT JALAN-POLI SPECIALIS KULIT',
            ],
            [
                'nama' => 'POLI SPECIALIS PARU',
                'kode_pendapatan' => '701.42',
                'desc_pendapatan' => 'PENDAPATAN RAWAT JALAN-POLI SPECIALIS PARU',
                'kode_biaya' => '801.42',
                'desc_biaya' => 'BIAYA RAWAT JALAN-POLI SPECIALIS PARU',
            ],
            [
                'nama' => 'POLI SPECIALIS ANESTESI',
                'kode_pendapatan' => '701.43',
                'desc_pendapatan' => 'PENDAPATAN RAWAT JALAN-POLI SPECIALIS ANESTESI',
                'kode_biaya' => '801.43',
                'desc_biaya' => 'BIAYA RAWAT JALAN-POLI SPECIALIS ANESTESI',
            ],
            [
                'nama' => 'POLI SPECIALIS ORTHOPEDI',
                'kode_pendapatan' => '701.44',
                'desc_pendapatan' => 'PENDAPATAN RAWAT JALAN-POLI SPECIALIS ORTHOPEDI',
                'kode_biaya' => '801.44',
                'desc_biaya' => 'BIAYA RAWAT JALAN-POLI SPECIALIS ORTHOPEDI',
            ],
            [
                'nama' => 'POLI SPECIALIS PATOLOGI KLINIK',
                'kode_pendapatan' => '701.45',
                'desc_pendapatan' => 'PENDAPATAN RAWAT JALAN-POLI SPECIALIS PATOLOGI KLINIK',
                'kode_biaya' => '801.45',
                'desc_biaya' => 'BIAYA RAWAT JALAN-POLI SPECIALIS PATOLOGI KLINIK',
            ],
            [
                'nama' => 'POLI ESTETIKA',
                'kode_pendapatan' => '701.46',
                'desc_pendapatan' => 'PENDAPATAN RAWAT JALAN-POLI ESTETIKA',
                'kode_biaya' => '801.46',
                'desc_biaya' => 'BIAYA RAWAT JALAN-POLI ESTETIKA',
            ],
            [
                'nama' => 'POLI TINDAKAN',
                'kode_pendapatan' => '701.47',
                'desc_pendapatan' => 'PENDAPATAN RAWAT JALAN-POLI TINDAKAN',
                'kode_biaya' => '801.47',
                'desc_biaya' => 'BIAYA RAWAT JALAN-POLI TINDAKAN',
            ],
            [
                'nama' => 'MCU',
                'kode_pendapatan' => '701.48',
                'desc_pendapatan' => 'PENDAPATAN RAWAT JALAN-MCU',
                'kode_biaya' => '801.48',
                'desc_biaya' => 'BIAYA RAWAT JALAN-MCU',
            ],
            [
                'nama' => 'POLI GIGI',
                'kode_pendapatan' => '701.50',
                'desc_pendapatan' => 'PENDAPATAN RAWAT JALAN-POLI GIGI',
                'kode_biaya' => '801.50',
                'desc_biaya' => 'BIAYA RAWAT JALAN-POLI GIGI',
            ],
            [
                'nama' => 'POLI SPECIALIS GIZI KLINIK',
                'kode_pendapatan' => '701.54',
                'desc_pendapatan' => 'PENDAPATAN RAWAT JALAN-POLI SPECIALIS GIZI KLINIK',
                'kode_biaya' => '801.54',
                'desc_biaya' => 'BIAYA RAWAT JALAN-POLI SPECIALIS GIZI KLINIK',
            ],
            [
                'nama' => 'DENTAL LAB',
                'kode_pendapatan' => '701.55',
                'desc_pendapatan' => 'PENDAPATAN RAWAT JALAN-DENTAL LAB',
                'kode_biaya' => '801.55',
                'desc_biaya' => 'BIAYA RAWAT JALAN-DENTAL LAB',
            ],
            [
                'nama' => 'FISIOTERAPHY',
                'kode_pendapatan' => '701.56',
                'desc_pendapatan' => 'PENDAPATAN RAWAT JALAN-FISIOTERAPHY',
                'kode_biaya' => '801.56',
                'desc_biaya' => 'BIAYA RAWAT JALAN-FISIOTERAPHY',
            ],
            [
                'nama' => 'POLI KONSULEN TUMBUH KEMBANG ANAK',
                'kode_pendapatan' => '701.26',
                'desc_pendapatan' => 'PENDAPATAN RAWAT JALAN-POLI KONSULEN TUMBUH KEMBANG ANAK',
                'kode_biaya' => '801.26',
                'desc_biaya' => 'BIAYA RAWAT JALAN-POLI KONSULEN TUMBUH KEMBANG ANAK',
            ],
            [
                'nama' => 'POLI SUB SPESIALIS KONSULTANT PSIKIATRI ANAK DAN REMAJA',
                'kode_pendapatan' => '701.27',
                'desc_pendapatan' => 'PENDAPATAN RAWAT JALAN-POLI SUB SPESIALIS KONSULTANT PSIKIATRI ANAK DAN REMAJA',
                'kode_biaya' => '801.27',
                'desc_biaya' => 'BIAYA RAWAT JALAN-POLI SUB SPESIALIS KONSULTANT PSIKIATRI ANAK DAN REMAJA',
            ],
            [
                'nama' => 'PHYSIOCENTER',
                'kode_pendapatan' => '701.28',
                'desc_pendapatan' => 'PENDAPATAN RAWAT JALAN-PHYSIOCENTER',
                'kode_biaya' => '801.28',
                'desc_biaya' => 'BIAYA RAWAT JALAN-PHYSIOCENTER',
            ],
            [
                'nama' => 'POLI PSIKOLOGI',
                'kode_pendapatan' => '701.11',
                'desc_pendapatan' => 'PENDAPATAN RAWAT JALAN-POLI PSIKOLOGI',
                'kode_biaya' => '801.11',
                'desc_biaya' => 'BIAYA RAWAT JALAN-POLI PSIKOLOGI',
            ],
            [
                'nama' => 'POLI BEDAH MULUT',
                'kode_pendapatan' => '701.13',
                'desc_pendapatan' => 'PENDAPATAN RAWAT JALAN-POLI BEDAH MULUT',
                'kode_biaya' => '801.13',
                'desc_biaya' => 'BIAYA RAWAT JALAN-POLI BEDAH MULUT',
            ],
            [
                'nama' => 'HOMECARE',
                'kode_pendapatan' => '701.51',
                'desc_pendapatan' => 'PENDAPATAN RAWAT JALAN-HOMECARE',
                'kode_biaya' => '801.51',
                'desc_biaya' => 'BIAYA RAWAT JALAN-HOMECARE',
            ],
            [
                'nama' => 'RAWAT INAP KELAS',
                'kode_pendapatan' => '702.12',
                'desc_pendapatan' => 'PENDAPATAN RAWAT INAP-RAWAT INAP KELAS',
                'kode_biaya' => '802.12',
                'desc_biaya' => 'BIAYA RAWAT INAP-RAWAT INAP KELAS',
            ],
            [
                'nama' => 'KAMAR OPERASI',
                'kode_pendapatan' => '702.19',
                'desc_pendapatan' => 'PENDAPATAN RAWAT INAP-KAMAR OPERASI',
                'kode_biaya' => '802.19',
                'desc_biaya' => 'BIAYA RAWAT INAP-KAMAR OPERASI',
            ],
            [
                'nama' => 'CSSD',
                'kode_pendapatan' => '702.96',
                'desc_pendapatan' => 'PENDAPATAN RAWAT INAP-CSSD',
                'kode_biaya' => '802.96',
                'desc_biaya' => 'BIAYA RAWAT INAP-CSSD',
            ],
            [
                'nama' => 'LABORATORIUM',
                'kode_pendapatan' => '703.78',
                'desc_pendapatan' => 'PENDAPATAN PENUNJANG MEDIS-LABORATORIUM',
                'kode_biaya' => '803.78',
                'desc_biaya' => 'BIAYA PENUNJANG MEDIS-LABORATORIUM',
                'kategori' => 'Penunjang Medis',
            ],
            [
                'nama' => 'RADIOLOGI',
                'kode_pendapatan' => '703.80',
                'desc_pendapatan' => 'PENDAPATAN PENUNJANG MEDIS-RADIOLOGI',
                'kode_biaya' => '803.80',
                'desc_biaya' => 'BIAYA PENUNJANG MEDIS-RADIOLOGI',
                'kategori' => 'Penunjang Medis',
            ],
            [
                'nama' => 'GIZI',
                'kode_pendapatan' => '703.85',
                'desc_pendapatan' => 'PENDAPATAN PENUNJANG MEDIS-GIZI',
                'kode_biaya' => '803.85',
                'desc_biaya' => 'BIAYA PENUNJANG MEDIS-GIZI',
                'kategori' => 'Penunjang Medis',
            ],
            [
                'nama' => 'GIZI (PROJECT)',
                'kode_pendapatan' => '703.86',
                'desc_pendapatan' => 'PENDAPATAN PENUNJANG MEDIS-GIZI (PROJECT)',
                'kode_biaya' => '803.86',
                'desc_biaya' => 'BIAYA PENUNJANG MEDIS-GIZI (PROJECT)',
                'kategori' => 'Penunjang Medis',
            ],
            [
                'nama' => 'REKAM MEDIS',
                'kode_pendapatan' => '703.87',
                'desc_pendapatan' => 'PENDAPATAN PENUNJANG MEDIS-REKAM MEDIS',
                'kode_biaya' => '803.87',
                'desc_biaya' => 'BIAYA PENUNJANG MEDIS-REKAM MEDIS',
                'kategori' => 'Penunjang Medis',
            ],
            [
                'nama' => 'FARMASI',
                'kode_pendapatan' => '704.82',
                'desc_pendapatan' => 'PENDAPATAN FARMASI-FARMASI',
                'kode_biaya' => '804.82',
                'desc_biaya' => 'BIAYA FARMASI-FARMASI',
                'kategori' => 'Penunjang Medis',
            ],
            [
                'nama' => 'FARMASI BMF (penjualan bebas cash, pama, p3k)',
                'kode_pendapatan' => '704.84',
                'desc_pendapatan' => 'PENDAPATAN FARMASI-FARMASI BMF (penjualan bebas cash, pama, p3k)',
                'kode_biaya' => '804.84',
                'desc_biaya' => 'BIAYA FARMASI-FARMASI BMF (penjualan bebas cash, pama, p3k)',
            ],
            [
                'nama' => 'TIM VERIFIKASI',
                'kode_pendapatan' => '705.06',
                'desc_pendapatan' => 'PENDAPATAN UMUM-TIM VERIFIKASI',
                'kode_biaya' => '832.06',
                'desc_biaya' => 'BIAYA PENUNJANG OPERASIONAL-TIM VERIFIKASI',
            ],
            [
                'nama' => 'PROJECT',
                'kode_pendapatan' => '705.69',
                'desc_pendapatan' => 'PENDAPATAN UMUM-PROJECT',
                'kode_biaya' => '832.69',
                'desc_biaya' => 'BIAYA PENUNJANG OPERASIONAL-PROJECT',
            ],
            [
                'nama' => 'AKUNTANSI & BENDAHARA',
                'kode_pendapatan' => '705.73',
                'desc_pendapatan' => 'PENDAPATAN UMUM-AKUNTANSI & BENDAHARA',
                'kode_biaya' => '832.73',
                'desc_biaya' => 'BIAYA PENUNJANG OPERASIONAL-AKUNTANSI & BENDAHARA',
            ],
            [
                'nama' => 'IGD, RAWAT INAP, INTENSIF & KAMAR OPERASI',
                'kode_pendapatan' => null,
                'desc_pendapatan' => null,
                'kode_biaya' => '801.08',
                'desc_biaya' => 'BIAYA RAWAT JALAN-IGD, RAWAT INAP, INTENSIF & KAMAR OPERASI',
            ],
            [
                'nama' => 'RAWAT JALAN',
                'kode_pendapatan' => null,
                'desc_pendapatan' => null,
                'kode_biaya' => '801.20',
                'desc_biaya' => 'BIAYA RAWAT JALAN-RAWAT JALAN',
            ],
            [
                'nama' => 'POLI UMUM, SPESIALIS & MCU',
                'kode_pendapatan' => null,
                'desc_pendapatan' => null,
                'kode_biaya' => '801.21',
                'desc_biaya' => 'BIAYA RAWAT JALAN-POLI UMUM, SPESIALIS & MCU',
            ],
            [
                'nama' => 'POLI GIGI, LAB GIGI & FISIOTERAPHY',
                'kode_pendapatan' => null,
                'desc_pendapatan' => null,
                'kode_biaya' => '801.49',
                'desc_biaya' => 'BIAYA RAWAT JALAN-POLI GIGI, LAB GIGI & FISIOTERAPHY',
            ],
            [
                'nama' => 'KEPERAWATAN',
                'kode_pendapatan' => null,
                'desc_pendapatan' => null,
                'kode_biaya' => '802.07',
                'desc_biaya' => 'BIAYA RAWAT INAP-KEPERAWATAN',
            ],
            [
                'nama' => 'RAWAT INAP',
                'kode_pendapatan' => null,
                'desc_pendapatan' => null,
                'kode_biaya' => '802.10',
                'desc_biaya' => 'BIAYA RAWAT INAP-RAWAT INAP',
            ],
            [
                'nama' => 'POLI JENAZAH',
                'kode_pendapatan' => null,
                'desc_pendapatan' => null,
                'kode_biaya' => '802.15',
                'desc_biaya' => 'BIAYA RAWAT INAP-POLI JENAZAH',
            ],
            [
                'nama' => 'ALIH DAYA',
                'kode_pendapatan' => null,
                'desc_pendapatan' => null,
                'kode_biaya' => '832.16',
                'desc_biaya' => 'BIAYA PENUNJANG OPERASIONAL-ALIH DAYA',
            ],
            [
                'nama' => 'PENUNJANG MEDIS',
                'kode_pendapatan' => null,
                'desc_pendapatan' => null,
                'kode_biaya' => '803.76',
                'desc_biaya' => 'BIAYA PENUNJANG MEDIS-PENUNJANG MEDIS',
                'kategori' => 'Penunjang Medis',
            ],
            [
                'nama' => 'DIREKTUR',
                'kode_pendapatan' => null,
                'desc_pendapatan' => null,
                'kode_biaya' => '831.01',
                'desc_biaya' => 'BIAYA MANAGEMEN-DIREKTUR',
            ],
            [
                'nama' => 'WAKIL DIREKTUR PELAYANAN MEDIS',
                'kode_pendapatan' => null,
                'desc_pendapatan' => null,
                'kode_biaya' => '831.05',
                'desc_biaya' => 'BIAYA MANAGEMEN-WAKIL DIREKTUR PELAYANAN MEDIS',
            ],
            [
                'nama' => 'WAKIL DIREKTUR UMUM & SDM',
                'kode_pendapatan' => null,
                'desc_pendapatan' => null,
                'kode_biaya' => '831.57',
                'desc_biaya' => 'BIAYA MANAGEMEN-WAKIL DIREKTUR UMUM & SDM',
            ],
            [
                'nama' => 'WAKIL DIREKTUR PENGEMBANGAN BISNIS',
                'kode_pendapatan' => null,
                'desc_pendapatan' => null,
                'kode_biaya' => '831.65',
                'desc_biaya' => 'BIAYA MANAGEMEN-WAKIL DIREKTUR PENGEMBANGAN BISNIS',
            ],
            [
                'nama' => 'WAKIL DIREKTUR KEUANGAN & SIM RS',
                'kode_pendapatan' => null,
                'desc_pendapatan' => null,
                'kode_biaya' => '831.71',
                'desc_biaya' => 'BIAYA MANAGEMEN-WAKIL DIREKTUR KEUANGAN & SIM RS',
            ],
            [
                'nama' => 'PENGURUS YAYASAN',
                'kode_pendapatan' => null,
                'desc_pendapatan' => null,
                'kode_biaya' => '831.99',
                'desc_biaya' => 'BIAYA MANAGEMEN-PENGURUS YAYASAN',
            ],
            [
                'nama' => 'SPI (SATUAN PENGAWAS INTERNAL)',
                'kode_pendapatan' => null,
                'desc_pendapatan' => null,
                'kode_biaya' => '832.02',
                'desc_biaya' => 'BIAYA PENUNJANG OPERASIONAL-SPI (SATUAN PENGAWAS INTERNAL)',
            ],
            [
                'nama' => 'STAFF MEDIS FUNGSIONAL (SMF)',
                'kode_pendapatan' => null,
                'desc_pendapatan' => null,
                'kode_biaya' => '832.03',
                'desc_biaya' => 'BIAYA PENUNJANG OPERASIONAL-STAFF MEDIS FUNGSIONAL (SMF)',
            ],
            [
                'nama' => 'SEKERTARIS',
                'kode_pendapatan' => null,
                'desc_pendapatan' => null,
                'kode_biaya' => '832.04',
                'desc_biaya' => 'BIAYA PENUNJANG OPERASIONAL-SEKERTARIS',
            ],
            [
                'nama' => 'SDM',
                'kode_pendapatan' => null,
                'desc_pendapatan' => null,
                'kode_biaya' => '832.58',
                'desc_biaya' => 'BIAYA PENUNJANG OPERASIONAL-SDM',
                'kategori' => 'SDM',
            ],
            [
                'nama' => 'FASILITAS UMUM',
                'kode_pendapatan' => null,
                'desc_pendapatan' => null,
                'kode_biaya' => '832.61',
                'desc_biaya' => 'BIAYA PENUNJANG OPERASIONAL-FASILITAS UMUM',
            ],
            [
                'nama' => 'LOGISTIK',
                'kode_pendapatan' => null,
                'desc_pendapatan' => null,
                'kode_biaya' => '832.63',
                'desc_biaya' => 'BIAYA PENUNJANG OPERASIONAL-LOGISTIK',
            ],
            [
                'nama' => 'UNIT USAHA',
                'kode_pendapatan' => null,
                'desc_pendapatan' => null,
                'kode_biaya' => '832.66',
                'desc_biaya' => 'BIAYA PENUNJANG OPERASIONAL-UNIT USAHA',
            ],
            [
                'nama' => 'PENGEMBANGAN PRODUK',
                'kode_pendapatan' => null,
                'desc_pendapatan' => null,
                'kode_biaya' => '832.70',
                'desc_biaya' => 'BIAYA PENUNJANG OPERASIONAL-PENGEMBANGAN PRODUK',
            ],
            [
                'nama' => 'ASURANSI & SIM RS',
                'kode_pendapatan' => null,
                'desc_pendapatan' => null,
                'kode_biaya' => '832.75',
                'desc_biaya' => 'BIAYA PENUNJANG OPERASIONAL-ASURANSI & SIM RS',
            ],
        ];

        foreach ($units as $unit) {
            Unit::create($unit);
        }
    }
}
